### ISSUE TITLE
I got error while i tried it hosting in a server

### ISSUE THREAD

**Issue by amiind** [SolanaNFTCollector/Solana-Minting-Bot#4]
> Bot started
> OS : Mac
> Traceback (most recent call last):
>   File "/app/main.py", line 26, in <module>
>    magiceden.mint(config, isWindows)
>    File "/app/magiceden.py", line 165, in mint
>     main_window = initWallet()
>   File "/app/magiceden.py", line 89, in initWallet
>     driver.switch_to.window(driver.window_handles[1])
>  IndexError: list index out of range

I found this error can u fix it?

**Comment by SolanaNFTCollector** [comment]
Hello, could you first tell me if you are using mac m1 or mac intel, I will try and see where the error is.

**Comment by amiind** [comment]
Its Ubuntu mate

**Comment by SolanaNFTCollector** [comment]
Oh sorry i didn't see it you wanted to host it on server. I do not support linux operation systems, but what you could try is replace in de "chromedriver" file inside the mac folder by the linux one available here [here](https://chromedriver.storage.googleapis.com/index.html?path=99.0.4844.51/)
But I have never tested this bot with linux so I cannot guarantee it will work. Tell me if this solution works.

**Comment by amiind** [comment]
Okay will update you

**Comment by Ruslan43223** [comment]
DevTools listening on ws://127.0.0.1:28335/devtools/browser/bbbb820d-febb-485f-a857-7b3151c14945
Assertion - successfully found chrome driver
Status - Initializing wallet
Event - switch window
[19524:9968:0305/205817.531:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: message, this is crbug.com/1216328.
[19524:9968:0305/205817.532:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[19524:9968:0305/205817.532:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this is crbug.com/1216328.
[19524:10704:0305/205817.549:ERROR:device_event_log_impl.cc(214)] [20:58:17.552] Bluetooth: bluetooth_adapter_winrt.cc:1075 Getting Default Adapter failed.
[19524:9968:0305/205817.549:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
Status - Finished Initializing wallet
Status - Selecting wallet on ME
 
![image](https://user-images.githubusercontent.com/81520996/156894918-5736f3e1-79f2-4da2-800f-edfd218016de.png)
 Do I need to press anything?

**Comment by Ruslan43223** [comment]
It automatically closes after a minute.

**Comment by Ruslan43223** [comment]
Traceback (most recent call last):
  File "C:\Users\Family\Desktop\Solana-Minting-Bot-main\main.py", line 26, in <module>
    magiceden.mint(config, isWindows)
  File "C:\Users\Family\Desktop\Solana-Minting-Bot-main\magiceden.py", line 173, in mint
    selectWallet()
  File "C:\Users\Family\Desktop\Solana-Minting-Bot-main\magiceden.py", line 35, in selectWallet
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "C:\Users\Family\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x009969A3+2582947]
	Ordinal0 [0x0092A6D1+2139857]
	Ordinal0 [0x00823A98+1063576]
	Ordinal0 [0x0084FF3E+1244990]
	Ordinal0 [0x0085013B+1245499]
	Ordinal0 [0x00879F52+1417042]
	Ordinal0 [0x00868594+1344916]
	Ordinal0 [0x0087834A+1409866]
	Ordinal0 [0x00868366+1344358]
	Ordinal0 [0x00845176+1200502]
	Ordinal0 [0x00846066+1204326]
	GetHandleVerifier [0x00B3BE02+1675858]
	GetHandleVerifier [0x00BF036C+2414524]
	GetHandleVerifier [0x00A2BB01+560977]
	GetHandleVerifier [0x00A2A8D3+556323]
	Ordinal0 [0x0093020E+2163214]
	Ordinal0 [0x00935078+2183288]
	Ordinal0 [0x009351C0+2183616]
	Ordinal0 [0x0093EE1C+2223644]
	BaseThreadInitThunk [0x76FEF989+25]
	RtlGetAppContainerNamedObjectPath [0x773D74A4+228]
	RtlGetAppContainerNamedObjectPath [0x773D7474+180]

>>>

**Comment by SolanaNFTCollector** [comment]
sorry if this happend to you, I will try finding a way to fix this. Next time please create a new issue.

**Comment by SolanaNFTCollector** [comment]
You do not need to touch anything

**Comment by Ruslan43223** [comment]
> Вам не нужно ничего трогать

if I don't touch it it just closes(

**Comment by SolanaNFTCollector** [comment]
Fixed the issue, please run 
`pip uninstall webdriver-manager`
and run
`python -m pip install git+https://github.com/np-8/webdriver_manager.git`

https://github.com/SolanaNFTCollector/Solana-Minting-Bot/commit/eca308cb0bfc1daf62b880047d55015ff82fb752

**Comment by aekirgil** [comment]
Hi,

this problem is still ongoing.  I am getting this error ->  <img width="630" alt="image" src="https://user-images.githubusercontent.com/608632/165097577-51a29ee1-9213-4d60-b6d3-d2f791a3a931.png">

**Comment by SolanaNFTCollector** [comment]
hello, could you please give me the complete logs, with os and chrome version ?
