### ISSUE TITLE
SOL left the wallet but no NFT

### ISSUE THREAD

**Issue by seuaCoder** [SolanaNFTCollector/Solana-Minting-Bot#51]
Hi,

i tried the bot, i paid for the NFT but i didn't receive the it.

`Found the mint button
Found the button
Traceback (most recent call last):
  File "/Users/mike/Work/Solana-Minting-Bot/main.py", line 26, in <module>
    magiceden.mint(config, isWindows)
  File "/Users/mike/Work/Solana-Minting-Bot/magiceden.py", line 153, in mint
    avaitMint()
  File "/Users/mike/Work/Solana-Minting-Bot/magiceden.py", line 107, in avaitMint
    WebDriverWait(driver, 60).until(EC.presence_of_element_located(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001084c62c9 chromedriver + 5120713
1   chromedriver                        0x0000000108454e33 chromedriver + 4656691
2   chromedriver                        0x0000000108044158 chromedriver + 393560
3   chromedriver                        0x0000000108078edd chromedriver + 610013
4   chromedriver                        0x0000000108079161 chromedriver + 610657
5   chromedriver                        0x00000001080ab244 chromedriver + 815684
6   chromedriver                        0x00000001080964ad chromedriver + 730285
7   chromedriver                        0x00000001080a8f41 chromedriver + 806721
8   chromedriver                        0x0000000108096373 chromedriver + 729971
9   chromedriver                        0x000000010806c609 chromedriver + 558601
10  chromedriver                        0x000000010806d635 chromedriver + 562741
11  chromedriver                        0x0000000108498b1d chromedriver + 4934429
12  chromedriver                        0x000000010849d295 chromedriver + 4952725
13  chromedriver                        0x00000001084a23cf chromedriver + 4973519
14  chromedriver                        0x000000010849dcba chromedriver + 4955322
15  chromedriver                        0x000000010847837c chromedriver + 4801404
16  chromedriver                        0x00000001084b7c68 chromedriver + 5061736
17  chromedriver                        0x00000001084b7def chromedriver + 5062127
18  chromedriver                        0x00000001084cd5e5 chromedriver + 5150181
19  libsystem_pthread.dylib             0x00007ff802c714e1 _pthread_start + 125
20  libsystem_pthread.dylib             0x00007ff802c6cf6b thread_start + 15
`

**Comment by seuaCoder** [comment]
seems that it's a rug, did you corrupt the code of the phantom extension ? :)
